### ISSUE TITLE
Services discovery times out

### ISSUE THREAD

**Issue by elvishribeiro** [weliem/blessed-bluez#11]
Hello Martijn,

I have some Nordic devices and I'm having a bit problem using your library. When I try to connect to the device it times out and doesn't respond to the services (Image 1). Odly, using gatttool  the services appear just after the connection has been succeeded (Image 2).

Do you have any idea what this could be? Something I'm missing?

Thanks in advance

P.S: Thank you for your lib, it's very well documentated.

![image](https://user-images.githubusercontent.com/43489254/163332872-35db607b-569f-4753-8ba3-2ed39b6208bd.png)
_[Image 1]_

![image](https://user-images.githubusercontent.com/43489254/163334144-35dff129-972a-4cfb-9114-d483025180c4.png)
_[Image 2]_

**Comment by weliem** [comment]
Not sure what it could be. It says in the log that the timeout was reached for service discovery. So it seems it is taking too long. Also the connection takes 7s according to log. Also very slow.

Is it your own device? Does it make sense everything is going so slow?

**Comment by weliem** [comment]
By the way, service discovery times out after 10s
