### ISSUE TITLE
com.github.weliem.blessed-bluez:blessed:jar:0.60 was not found in https://jitpack.io 

### ISSUE THREAD

**Issue by cyberp** [weliem/blessed-bluez#12]
Hi,

thank you for the great work on this project. I try to update my project that is using blessed-bluez to version 0.60. But it seems that the jar in jitpack.io is missing. 

Maven error:

`com.github.weliem.blessed-bluez:blessed:jar:0.60 was not found in https://jitpack.io during a previous attempt.`

The jar artifcat is missing n the [build log](https://jitpack.io/com/github/weliem/blessed-bluez/0.60/build.log) too.

Could you check this?

**Comment by weliem** [comment]
I think you got the package name wrong. It should be com.github.weliem.blessed-bluez:blessed:0.60

**Comment by cyberp** [comment]
You are right.
I got the package name wrong.

But the information from jitpack.io are a little bit mysterious.
I use maven. 

If you copy the dependecy node from [startpage of https://jitpack.io/#weliem/blessed-bluez](https://jitpack.io/#weliem/blessed-bluez) without selecting a version you get:

```
<dependency>
	    <groupId>com.github.weliem</groupId>
	    <artifactId>blessed-bluez</artifactId>
	    <version>Tag</version>
</dependency>
```
That works with version 0.60.
But if you are select a version like 0.60 or 0.51 and then copy the dependecy node, you get:

```
<dependency>
	    <groupId>com.github.weliem.blessed-bluez</groupId>
	    <artifactId>blessed</artifactId>
	    <version>0.60</version>
</dependency>
```

That is not working any more for version 0.60, but for version 0.51

**Comment by morimoriysmoon** [comment]
I have the same issue.
