### ISSUE TITLE
Build of 0.60 somehow did not work

### ISSUE THREAD

**Issue by danielgruber** [weliem/blessed-bluez#15]
The build of your library for 0.60 did not go through, see https://jitpack.io/com/github/weliem/blessed-bluez/0.60/build.log

Do you still maintain this?

**Comment by weliem** [comment]
The log looks fine to me...what makes you think it didn't work?

**Comment by danielgruber** [comment]
Due to this:

 ⚠️   WARNING:
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.
 See the documentation and examples: https://jitpack.io/docs/
 
We are also unable to integrate 0.60, but it’s possible with 0.51

**Comment by Stephen-Hamilton-C** [comment]
I'm having the same issue with 0.60. When I add it to an empty project, I can't import anything from blessed-bluez. However, when downgrading to 0.51, everything works as expected.

**Comment by weliem** [comment]
I made some changes and published 0.61. Tried to import it in a new project and everything seems fine...

Can you try?

**Comment by Stephen-Hamilton-C** [comment]
That fixed it. Thanks!

Also don't forget to update your README with the latest version
