### ISSUE TITLE
How to get advertising package by bluez?

### ISSUE THREAD

**Issue by zhuyuemings** [weliem/blessed-bluez#16]
i need to get advertising package to verify something, but i can only get manufacturer data from scan result,

**Comment by weliem** [comment]
Bluez doesn't provide access to the lowlevel advertisement (yet).

What do you need?

**Comment by zhuyuemings** [comment]
I tried to get the advertising package(broadcast message?) like this:
![image](https://user-images.githubusercontent.com/25892334/197668449-991500e5-43f9-47ac-8bb1-8b2e18715ea3.png)
but only get manufacturer data from scan result, like this:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/25892334/197668688-d1c45942-7fbb-4654-b7d8-9e7727e6737e.png">

**Comment by ranjitIN** [comment]
if your device advertise this details you can get this advertisement data
