### ISSUE TITLE
remaining thread did not shutdown?

### ISSUE THREAD

**Issue by zhuyuemings** [weliem/blessed-bluez#17]
remaining thread: Thread[main,5,main]:isAlive=true
remaining thread: Thread[DBusConnection,5,main]:isAlive=true
remaining thread: Thread[DBus Sender Thread-1,5,main]:isAlive=true
remaining thread: Thread[DbusWorkerThreads1,5,main]:isAlive=true
remaining thread: Thread[Central-callback,5,main]:isAlive=true
remaining thread: Thread[Central-queue,5,main]:isAlive=true
remaining thread: Thread[Central-signal,5,main]:isAlive=true

**Comment by zhuyuemings** [comment]
i add those code to stop remaining thread in BluetoothCentralManager.java
`
public void shutdown(){
        callBackHandler.shutdown();
        queueHandler.shutdown();
        signalHandler.shutdown();
        try {
            adapter.getDBusConnection().close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
`

**Comment by weliem** [comment]
Please raise a PR. Looks like a good addition...

**Comment by weliem** [comment]
Thanks for the PR, merged it
