### ISSUE TITLE
Build instructions, and Java dependencies

### ISSUE THREAD

**Issue by d-f-clark** [weliem/blessed-bluez#2]
This package looks great, just what I need.  I'm building on a Raspberry Pi using the Buster version of Raspbian, with OpenJD K 11.  Could you provide guidance on any Java dependencies in the project, and some build instructions?  Thanks

**Comment by weliem** [comment]
Hi, I just updated the readme with some more information.

Let me know if this is sufficient!

**Comment by d-f-clark** [comment]
Thank you, and thanks for the quick response.

It looks like the only difference for the build.gradle file is the addition of the jitpack line, is that correct?  I don’t typically use gradle so I’m stumbling along trying to get the various components needed onto my Raspberry Pi, and get this library built.

I made the change in the build.gradle file, then started gradle and ran the build command (“gradle build”).  That produced a bunch of errors, as shown in the attached file.  Hopefully you have some insight into what’s happening.

Also, it seems that there is a Java dependency in the build.gradle file for Java 1.8 - I’ve got OpenJDK 11, which reports it’s version as 11.0.6.

Thanks for your help.

**Comment by d-f-clark** [comment]
I’ve just tried again with what I think are the proper changes to the build.gradle file, and again got a bunch of errors.  Files attached.

**Comment by weliem** [comment]
I can't see your attachments. Please paste some relevant lines as text in a comment.

OpenJDK 11 shouldnt be a problem. I only set the compatibility level to a minimum of 8....

**Comment by weliem** [comment]
If you simply clone the entire project and run 'gradle build', it should work on a Pi4

**Comment by d-f-clark** [comment]
Running on a RPi3, but I imagine that should be good enough.

I did clone the repository onto the RPi, then ran 'gradle build', produced a bunch of errors (see below).  The build.gradle from the clone doesn't match the change in the README.md that you made today. 

~/RelatedTools/theclone $ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/Kingston/RelatedTools/theclone/build.gradle' line: 22

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve org.jetbrains:annotations:16.0.2.
     Required by:
         project :
         project : > project :blessed
      > Could not resolve org.jetbrains:annotations:16.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/annotations/16.0.2/annotations-16.0.2.pom'.
            > org.apache.http.ssl.SSLInitializationException: /snap/gradle/91/usr/lib/jvm/java-11-openjdk-armhf/lib/security/cacerts (No such file or directory)
   > Could not resolve ch.qos.logback:logback-core:+.
     Required by:
         project :
      > Failed to list versions for ch.qos.logback:logback-core.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/maven-metadata.xml.
            > Could not get resource 'https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/maven-metadata.xml'.
               > org.apache.http.ssl.SSLInitializationException: /snap/gradle/91/usr/lib/jvm/java-11-openjdk-armhf/lib/security/cacerts (No such file or directory)
   > Could not resolve ch.qos.logback:logback-classic:+.
     Required by:
         project :
      > Failed to list versions for ch.qos.logback:logback-classic.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/maven-metadata.xml.
            > Could not get resource 'https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/maven-metadata.xml'.
               > org.apache.http.ssl.SSLInitializationException: /snap/gradle/91/usr/lib/jvm/java-11-openjdk-armhf/lib/security/cacerts (No such file or directory)
   > Could not resolve com.github.hypfvieh:dbus-java:3.3.0.
     Required by:
         project : > project :blessed
      > Could not resolve com.github.hypfvieh:dbus-java:3.3.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/hypfvieh/dbus-java/3.3.0/dbus-java-3.3.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /snap/gradle/91/usr/lib/jvm/java-11-openjdk-armhf/lib/security/cacerts (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s

[gradle_build3.log](https://github.com/weliem/blessed-bluez/files/6565330/gradle_build3.log)

**Comment by weliem** [comment]
Looks like gradle cannot find the OpenJDK cacerts file.

Sounds like you're have this issue:
https://stackoverflow.com/questions/31132751/gradle-can-not-find-cacerts-file-wrong-direcrory-looked-up

**Comment by weliem** [comment]
Any update?

**Comment by d-f-clark** [comment]
Given up, no time to solve gradle issues apparently caused by snap.

**Comment by d-f-clark** [comment]
Thanks for your attempts to help.

**Comment by weliem** [comment]
Sorry to hear, but no worries!

**Comment by weliem** [comment]
I see that the project doesn't build when using gradle 7. I have pushed a fixed. 

Please try again

**Comment by d-f-clark** [comment]
That worked, thanks!  The gradle build did produce some errors, in the test phase.  Log file is attached.
[build_log.txt](https://github.com/weliem/blessed-bluez/files/6640846/build_log.txt)

**Comment by weliem** [comment]
I see the Pi3 is a bit slower than my tests expect. I updated the tests to be more lenient.

Please try again

**Comment by d-f-clark** [comment]
I'll try the build again, but since the jar file built successfully I thought I'd try to add the BluetoothHandler into a test app that I have.  Instantiation of BluetoothHandler class fails on a class-not-found exception.  Seems this library depends on org.freedesktop?  What components?

13:32:44.837 [main] INFO  testapp.BLEpoller.AdvertisementPoller - initializing BluetoothCentral
Exception in thread "main" 
java.lang.NoClassDefFoundError: org/freedesktop/dbus/exceptions/DBusException
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at approach.BLEpoller.BluetoothHandler.<init>(BluetoothHandler.java:258)
	at approach.Approach.main(Approach.java:71)
Caused by: java.lang.ClassNotFoundException: org.freedesktop.dbus.exceptions.DBusException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

**Comment by weliem** [comment]
hmmm, that is odd. Looks like it can't find class files that should be there.

Are you able to run the demo app? After doing a 'gradle build' you can start it using:
`java -jar build/libs/blessed-test-0.2-App.jar
`

How did you include Blessed in your project? Using gradle?
