### ISSUE TITLE
I there any way to get battery info of a bluetooth device without connecting to it ?

### ISSUE THREAD

**Issue by ranjitIN** [weliem/blessed-bluez#23]
lets assume we have a BLE device i want to get the battery label of the Bluetooth device before connecting to it. 
is there any way to get the battery label of device before connecting to it.

**Comment by weliem** [comment]
Unless the battery level is in the advertisement data, it is not possible to get it without connecting first

**Comment by ranjitIN** [comment]
thanks i got it.
