### ISSUE TITLE
Can I submit a PR for updating dbus-java to 4.x.x?

### ISSUE THREAD

**Issue by satsen** [weliem/blessed-bluez#34]
In dbus-java 4.x.x, there are different transports available other than just the JNR-based transport which brings in a bunch of native libraries for different platforms.

So I wanted to know if it will be merged in case I open a pull request that updates dbus-java to 4.3.2. The difference is that the minimum supported Java version for 4.3.2 is Java 11. dbus-java 5.x.x requires Java 17+. So I'm hoping it's ok to migrate to 4.3.2 and thus move the minimum support to 11, so that we can use the improved dbus-java in this project.

Other than that, there are a number of improvements that can be made to the code (non-API-breaking), let me know in case they would be welcome. This is a great library and I'm willing to improve it and also publish it to the maven central

**Comment by weliem** [comment]
yes, sure. I haven't touched this library much lately so feel free to update it.
