### ISSUE TITLE
DBUS_EXECUTION_EXCEPTION

### ISSUE THREAD

**Issue by engineearemotetechnologiessl** [weliem/blessed-bluez#6]
Many DBUS_EXECUTION_EXCEPTION exceptions are thrown when trying to connect. After the exception is thrown, if you connect and disconnect using bluetoothctl , then the next connection attempt works correctly.

**Comment by weliem** [comment]
Can you share some mote information? For example a log so I can see what's happening?

**Comment by engineearemotetechnologiessl** [comment]
It seems like between the time that the device is discovered and connection attempt is made, scan is stopped.
If you want i can monitor dbus to get more information

Thanks

``10:03:36.287 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - DE:7D:87:73:77:0A    | -49   | connectable     | 1h 1.286s  | 4934807f-6c18-49fa-a433-e9ed38a7bc60    
10:03:36.287 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - Last BeaconDump status is : null
10:03:36.287 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - We should download start downloading!!
10:03:36.476 [Central-callback] [DEBUG] Utils                          - CB:2A:CC:32:94:57 (-65 >>  		 05 04 45 51 07 03 00 0E 01 2A BD 00 0D 80 00 00
10:03:36.476 [Central-callback] [DEBUG] Utils                          - CB:2A:CC:32:94:57 (-65 >>  		 00 00 26 F9 FA 00 FD
10:03:36.629 [Central-callback] [DEBUG] Utils                          - E1:B8:4E:E9:C7:4F (-54 >>  		 05 04 45 51 07 02 00 28 05 0F AB 00 0E 00 00 00
10:03:36.629 [Central-callback] [DEBUG] Utils                          - E1:B8:4E:E9:C7:4F (-54 >>  		 00 00 37 87 EE 81 81
10:03:36.975 [Central-callback] [DEBUG] Utils                          - EE:DC:23:67:9D:9D (-66 >>  		 05 05 45 50 01 04 00 21 01 2A BD 00 0C A6 00 00
10:03:36.975 [Central-callback] [DEBUG] Utils                          - EE:DC:23:67:9D:9D (-66 >>  		 00 00 00 00 34
10:03:36.976 [Central-callback] [DEBUG] Utils                          - C1:59:F2:C8:0B:1D (-67 >>  		 05 05 52 50 01 04 00 21 01 2A BD B7 0C A6 00 00
10:03:36.976 [Central-callback] [DEBUG] Utils                          - C1:59:F2:C8:0B:1D (-67 >>  		 00 00 00 00 34
10:03:37.669 [Central-callback] [DEBUG] Utils                          - E1:BE:5A:22:7D:4D (-58 >>  		 02 01 45 43 01 02 81 35 01 64 2D 2F 1F
10:03:37.693 [Central-callback] [DEBUG] Utils                          - FF:F4:7B:55:8B:C9 (-61 >>  		 05 04 45 51 07 03 00 0F 01 2A C0 00 0E 80 00 00
10:03:37.694 [Central-callback] [DEBUG] Utils                          - FF:F4:7B:55:8B:C9 (-61 >>  		 00 00 26 F2 FE 03 FD
10:03:37.789 [Central-callback] [DEBUG] Utils                          - F9:1F:FC:85:F3:64 (-64 >>  		 05 05 45 50 01 04 00 22 01 2A BF 00 0C A3 00 00
10:03:37.789 [Central-callback] [DEBUG] Utils                          - F9:1F:FC:85:F3:64 (-64 >>  		 00 00 00 00 34
10:03:38.399 [Central-callback] [DEBUG] Utils                          - DE:7D:87:73:77:0A (-47 >>  		 AA FE 00 04 49 34 80 7F 6C 18 49 FA A4 33 E9 ED
10:03:38.399 [Central-callback] [DEBUG] Utils                          - DE:7D:87:73:77:0A (-47 >>  		 38 A7 BC 60 00 00
10:03:38.399 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - --------------------------------------------------------------------------------
10:03:38.399 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - DE:7D:87:73:77:0A    | -46   | connectable     | 1h 3.399s  | 4934807f-6c18-49fa-a433-e9ed38a7bc60    
10:03:38.400 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - Last BeaconDump status is : null
10:03:38.400 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - We should download start downloading!!
10:03:38.400 [Central-callback] [INFO ] BluetoothHandler               - Found advertising and not in blacklist.. Attempting to connect
10:03:38.458 [Central-signal ] [INFO ] BluetoothCentralManager        - scan stopped
10:03:39.064 [Central-queue  ] [INFO ] BluetoothPeripheral            - peripheral is connecting
10:03:39.065 [Central-queue  ] [INFO ] BluetoothPeripheral            - connecting to '' (DE:7D:87:73:77:0A)
10:03:45.509 [Central-queue  ] [ERROR] BluetoothPeripheral            - Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
10:03:45.509 [Central-queue  ] [ERROR] BluetoothPeripheral            - connection failed with status 'DBUS_EXECUTION_EXCEPTION'
10:03:45.510 [Central-callback] [INFO ] BluetoothHandler               - connection failed with status DBUS_EXECUTION_EXCEPTION with peripheral DE:7D:87:73:77:0A 
10:03:45.663 [pool-6-thread-1] [INFO ] SyncThread                     - Sync Items started 
10:03:45.838 [pool-6-thread-1] [INFO ] RestUtils                      - Http Post Successfully sent to server /sync?repositories=FullItemSnapshotItemRepository&offset=2994053
10:03:45.842 [pool-6-thread-1] [INFO ] SyncThread                     - Sync BeaconDumps started 
10:03:45.884 [pool-6-thread-1] [INFO ] RestUtils                      - Http Post Successfully sent to server /sync?repositories=BeaconDumpRepository&offset=2993843
10:03:45.886 [pool-6-thread-1] [INFO ] NetworkStatusThread            - onSync:: OnSync received with list size: 0, error: false
10:03:45.886 [pool-6-thread-1] [INFO ] AdvertisingRegistryBlessed     - Since last check found advertisings are: 214
10:03:45.886 [pool-6-thread-1] [INFO ] SentinelAdvertisingAccumulator - Added advertisings to queue: 9
10:03:45.886 [pool-6-thread-1] [INFO ] DeviceMessageConsumer          - Added 0 new items
10:03:45.886 [pool-6-thread-1] [INFO ] DeviceMessageConsumer          - Sent advertising since last check: 3
10:03:50.541 [Central-signal ] [INFO ] BluetoothCentralManager        - scan started
10:03:51.662 [Central-callback] [DEBUG] Utils                          - CB:2A:CC:32:94:57 (-61 >>  		 05 04 45 51 07 03 00 0E 01 2A BD 00 0D 80 00 00
10:03:51.662 [Central-callback] [DEBUG] Utils                          - CB:2A:CC:32:94:57 (-61 >>  		 00 00 26 F9 FA 00 FD
10:03:51.803 [Central-callback] [DEBUG] Utils                          - E1:B8:4E:E9:C7:4F (-62 >>  		 05 04 45 51 07 02 00 28 05 0F AB 00 0E 00 00 00
10:03:51.803 [Central-callback] [DEBUG] Utils                          - E1:B8:4E:E9:C7:4F (-62 >>  		 00 00 37 88 EE 81 81
10:03:52.272 [Central-callback] [DEBUG] Utils                          - DE:7D:87:73:77:0A (-49 >>  		 AA FE 00 04 49 34 80 7F 6C 18 49 FA A4 33 E9 ED
10:03:52.272 [Central-callback] [DEBUG] Utils                          - DE:7D:87:73:77:0A (-49 >>  		 38 A7 BC 60 00 00
10:03:52.273 [Central-callback] [INFO ] AdvertisingRegistryBlessed     - -----------------------------------------------------------------------

**Comment by weliem** [comment]
I have seen this occasionally also. It almost looks like the peripheral hasn't been created properly on the dbus. You could try adding a longer delay before connecting....but I have no clue what is causing this issue. You could try using btmon to see what is happening? I think it is a Bluez bug but I am not sure.

And indeed I am stopping the scan before connecting. Some adapters cant handle connecting while scanning. Scanning will be resumed automatically after the connection succeeds or fails.

**Comment by wangjianxiang** [comment]
What is the Bluetooth version of your device？

**Comment by weliem** [comment]
Your issue could be causes by the stopScan() being called before connecting. I removed that in the latest release (0.50). Please have a look if that fixes your issue.
