### ISSUE TITLE
Advertise as Peripheral

### ISSUE THREAD

**Issue by ryanthon** [weliem/blessed-bluez#7]
Hi,

I was wondering if there was any functionality/documentation provided by this library for advertising as a peripheral? Basically the equivalent of CBPeripheralManager on iOS. For example, for broadcasting Eddystone or iBeacon?

Thank you

**Comment by weliem** [comment]
Unfortunately not yet. I needed peripheral support so that was the priority. Maybe I will add Central support in the future but I have no concrete plans for it.

Feel free to contribute if you want!
